spring.application.name=RestaurantBackend


# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/smart-restaurant-v2
spring.datasource.username=postgres
spring.datasource.password=23120355Hcmus*

# JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cloudinary
cloudinary.cloud-name=djhslhyp4
cloudinary.api-key=324165565482643
cloudinary.api-secret=OsfV10CtxjLmLyYclv9oBB6PN1o